const defaults={wage:0,partner:0,rentTwo:0,bills:[]};
function restoreData(){const saved=JSON.parse(localStorage.getItem('money-map-data')||'null')||structuredClone(defaults);delete saved.rentOne;saved.bills=(saved.bills||[]).map((bill,i)=>Array.isArray(bill)?{id:`bill-${i}`,name:bill[0],amount:bill[1],day:bill[2],frequency:'monthly',month:0}:bill);return saved}let data=restoreData();
let cursor=new Date();cursor.setDate(1);let bankHolidays=new Set();
let savingSettings=false;
let originalTheme,originalMode;
let planDirty=false;
let activeView='list';
const themes=[['sage','Sage'],['ocean','Ocean'],['plum','Plum']];
let theme=localStorage.getItem('money-map-theme')||'sage',mode=localStorage.getItem('money-map-mode')||'light';
const themeColours={sage:['#d8e7d9','#2b6c4c'],ocean:['#cce9ee','#167187'],plum:['#ead9e8','#79436e']};
function applyAppearance(){document.documentElement.dataset.theme=theme;document.documentElement.dataset.mode=mode}
function setPlanDirty(dirty=true){planDirty=dirty;document.querySelector('#saveSettings').disabled=!planDirty}
function renderAppearanceEditor(){const chosen=document.querySelector('#themeSelect');chosen.value=theme;document.querySelector('#darkModeInput').checked=mode==='dark';updateThemePreview();}
function updateThemePreview(){const selected=document.querySelector('#themeSelect').value,[soft,accent]=themeColours[selected];document.querySelector('#themePreview').style.setProperty('--preview-soft',soft);document.querySelector('#themePreview').style.setProperty('--preview-accent',accent)}
const money=v=>new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP'}).format(v);
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const nonWorking=d=>d.getDay()===0||d.getDay()===6||bankHolidays.has(dateKey(d));
const previousWorkingDay=(y,m,d)=>{const x=new Date(y,m,d);while(nonWorking(x))x.setDate(x.getDate()-1);return x};
const nextWorkingDay=(y,m,d)=>{const x=new Date(y,m,d);while(nonWorking(x))x.setDate(x.getDate()+1);return x};
const calendarDate=(y,m,d)=>new Date(y,m,Math.min(d,new Date(y,m+1,0).getDate()));
const nextWorkingBillDate=(y,m,d)=>{const x=calendarDate(y,m,d);while(nonWorking(x))x.setDate(x.getDate()+1);return x};
const sameDate=(a,b)=>a.toDateString()===b.toDateString();
const suffix=d=>d%10===1&&d!==11?'st':d%10===2&&d!==12?'nd':d%10===3&&d!==13?'rd':'th';
function payments(){const y=cursor.getFullYear(),m=cursor.getMonth(),items=[];
 for(let offset=-1;offset<=1;offset++){const date=new Date(y,m+offset,1),year=date.getFullYear(),month=date.getMonth();
  if(data.wage>0)items.push({name:'Monthly wage',amount:data.wage,date:previousWorkingDay(year,month,27),type:'income',category:'income',note:'Payday: moved back for weekends or bank holidays'});
  if(data.partner>0){items.push({name:'Partner rent contribution',amount:data.partner,date:previousWorkingDay(year,month,22),type:'income',category:'income',note:'Expected in before it is paid to rent'});items.push({name:'Partner rent contribution paid',amount:data.partner,date:previousWorkingDay(year,month,22),type:'outgoing',category:'rent',note:'Paid to rent: moved back for weekends or bank holidays'})}
  if(data.rentTwo>0)items.push({name:'Your rent payment',amount:data.rentTwo,date:previousWorkingDay(year,month,27),type:'outgoing',category:'rent',note:'Rent / payday: moved back for weekends or bank holidays'});
  data.bills.forEach(bill=>{if(bill.frequency==='annual'){if(month!==Number(bill.month))return;items.push({name:bill.name,amount:bill.amount,date:new Date(year,month,1),type:'outgoing',category:'bill',monthOnly:true,note:'Annual reminder — due sometime this month'})}else if(bill.frequency==='one-off'){if(!bill.date)return;const due=new Date(`${bill.date}T00:00:00`);if(due.getFullYear()===year&&due.getMonth()===month)items.push({name:bill.name,amount:bill.amount,date:due,type:'outgoing',category:'bill',note:'One-off payment'})}else if(bill.frequency==='window'){const start=Number(bill.startDay||1),end=Number(bill.endDay||start);items.push({name:bill.name,amount:bill.amount,date:nextWorkingBillDate(year,month,start),type:'outgoing',category:'bill',window:true,start,end,note:`Expected between the ${start}${suffix(start)} and ${end}${suffix(end)}`})}else{items.push({name:bill.name,amount:bill.amount,date:nextWorkingBillDate(year,month,bill.day),type:'outgoing',category:'bill',variable:bill.frequency==='variable',note:bill.frequency==='variable'?'Estimated monthly amount — update when confirmed':`Usual ${bill.day}${suffix(bill.day)} payment — moves to next working day`})}});
 }return items.filter(item=>item.date.getFullYear()===y&&item.date.getMonth()===m).sort((a,b)=>a.date-b.date)}
const paidKey=i=>`money-map-paid-${cursor.getFullYear()}-${cursor.getMonth()}-${i.type}-${i.name}-${i.amount}-${i.date.getDate()}`;
const actualKey=i=>`money-map-actual-${cursor.getFullYear()}-${cursor.getMonth()}-${i.name}-${i.date.getDate()}`;
function render(){const list=payments(),actualAmount=i=>Number(localStorage.getItem(actualKey(i)))||i.amount,bills=list.filter(i=>i.category==='bill').reduce((s,i)=>s+actualAmount(i),0),income=list.filter(i=>i.type==='income').reduce((s,i)=>s+actualAmount(i),0),outgoing=list.filter(i=>i.type==='outgoing').reduce((s,i)=>s+actualAmount(i),0),leftover=income-outgoing,billCount=list.filter(i=>i.category==='bill').length;
 document.querySelector('#monthTitle').textContent=cursor.toLocaleDateString('en-GB',{month:'long',year:'numeric'});document.querySelector('#leftover').textContent=money(leftover);document.querySelector('#incomeTotal').textContent=money(income);document.querySelector('#outgoingTotal').textContent=money(outgoing);document.querySelector('#billsTotal').textContent=money(bills);document.querySelector('#billsCount').textContent=`${billCount} ${billCount===1?'payment':'payments'} scheduled`;document.querySelector('#summaryLine').textContent=`${money(income)} expected in · ${money(outgoing)} planned out`;document.querySelector('#percentage').textContent=income?`${Math.round((outgoing/income)*100)}%`:'0%';
 const today=new Date(),next=list.find(i=>i.type==='outgoing'&&!localStorage.getItem(paidKey(i))&&(i.monthOnly||i.date>=new Date(today.getFullYear(),today.getMonth(),today.getDate())))||list.find(i=>i.type==='outgoing'&&!localStorage.getItem(paidKey(i)));document.querySelector('#nextUp').innerHTML=next?`<div class="next-card"><div><small>NEXT UP</small><strong>${next.name}</strong></div><div><b>${money(Number(localStorage.getItem(actualKey(next)))||next.amount)}</b><small>${next.window?`${next.start}–${next.end} ${cursor.toLocaleDateString('en-GB',{month:'short'})}`:next.monthOnly?'THIS MONTH':next.date.toLocaleDateString('en-GB',{day:'numeric',month:'short'})}</small></div></div>`:'';document.querySelector('#paymentList').innerHTML=list.map(i=>{const checked=localStorage.getItem(paidKey(i))==='true',actual=Number(localStorage.getItem(actualKey(i)))||i.amount;return `<article class="payment ${i.window?'window':''} ${i.type} ${i.category} ${sameDate(i.date,today)?'today':''}"><div class="date-box"><small>${i.window?'EXPECTED':i.monthOnly?'MONTH':i.date.toLocaleDateString('en-GB',{weekday:'short'}).toUpperCase()}</small>${i.window?`${i.start}–${i.end}`:i.monthOnly?'':i.date.getDate()}</div><div><div class="payment-name">${i.name}</div><div class="payment-meta">${i.note}</div>${i.category==='bill'?`<button class="details-button" data-details="${i.name}">Details</button>`:''}</div><div><div class="amount ${i.type==='income'?'income':''}">${i.type==='income'?'+':'−'}${money(actual)}</div>${i.variable?`<button class="actual-button" data-actual="${actualKey(i)}" data-estimate="${i.amount}">Set actual</button>`:''}<label class="paid-toggle"><input type="checkbox" data-key="${paidKey(i)}" ${checked?'checked':''}> ${i.type==='income'?'received':i.monthOnly?'booked / paid':'paid'}</label></div></article>`}).join('');document.querySelectorAll('[data-key]').forEach(b=>b.onchange=e=>{localStorage.setItem(e.target.dataset.key,e.target.checked);render()});document.querySelectorAll('[data-actual]').forEach(b=>b.onclick=()=>{const value=window.prompt('Enter the actual amount paid for this month:',b.dataset.estimate);if(value!==null&&!Number.isNaN(Number(value))){localStorage.setItem(b.dataset.actual,Number(value));render()}});document.querySelectorAll('[data-details]').forEach(b=>b.onclick=()=>openDetails(b.dataset.details));renderCalendar(list,today)}
function renderCalendar(list,today){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=(first.getDay()+6)%7,labels=['MON','TUE','WED','THU','FRI','SAT','SUN'];let html=labels.map(d=>`<div class="calendar-weekday">${d}</div>`).join('');for(let i=0;i<start;i++)html+='<div class="calendar-day empty"></div>';for(let day=1;day<=days;day++){const windows=list.filter(i=>i.window&&day>=i.start&&day<=i.end),events=list.filter(i=>!i.monthOnly&&!i.window&&i.date.getDate()===day),reminders=list.filter(i=>i.monthOnly&&day===1);html+=`<div class="calendar-day ${windows.length?'window-day':''} ${sameDate(new Date(y,m,day),today)?'today':''}"><div class="calendar-date">${day}</div>${[...events,...reminders].map(i=>`<span class="calendar-item ${i.type==='income'?'income':i.category==='rent'?'rent':''}">${i.name}</span>`).join('')}${windows.map(i=>{const middle=Math.floor((i.start+i.end)/2);return `<span class="calendar-window ${day===i.start?'start':''} ${day===i.end?'end':''}">${day===middle?`${i.name} · ${i.start}–${i.end}`:''}</span>`}).join('')}</div>`}document.querySelector('#calendarView').innerHTML=html}
const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
function billRow(b,i){const type=b.frequency||'monthly',field=type==='annual'?`<select aria-label="Due month" data-f="month">${months.map((name,n)=>`<option value="${n}" ${n===Number(b.month)?'selected':''}>${name}</option>`).join('')}</select>`:type==='one-off'?`<input aria-label="One-off date" type="date" value="${b.date||''}" data-f="date">`:type==='window'?`<input aria-label="Expected date window" value="${b.startDay||1}-${b.endDay||14}" data-f="window" placeholder="8-14">`:`<input aria-label="Day" type="number" min="1" max="31" value="${b.day}" data-f="day">`;return `<div class="bill-row"><input aria-label="Bill name" value="${b.name}" data-f="name"><input aria-label="Amount" type="number" step="0.01" value="${b.amount}" data-f="amount"><select aria-label="Frequency" data-f="frequency"><option value="monthly" ${type==='monthly'?'selected':''}>Monthly</option><option value="variable" ${type==='variable'?'selected':''}>Monthly variable</option><option value="annual" ${type==='annual'?'selected':''}>Annual month</option><option value="one-off" ${type==='one-off'?'selected':''}>One-off</option><option value="window" ${type==='window'?'selected':''}>Monthly window</option></select>${field}<button type="button" class="remove-bill" aria-label="Remove ${b.name}" data-remove="${i}">×</button></div>`}
function renderBillEditor(){document.querySelector('#billEditor').innerHTML=data.bills.map(billRow).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.remove),name=data.bills[i].name;if(window.confirm(`Remove ${name}? This can only be restored by adding it again.`)){data.bills.splice(i,1);setPlanDirty();renderBillEditor()}});document.querySelectorAll('.bill-row input,.bill-row select').forEach(input=>input.oninput=()=>setPlanDirty());document.querySelectorAll('[data-f=frequency]').forEach(select=>select.onchange=()=>{setPlanDirty();const row=select.closest('.bill-row'),index=[...document.querySelectorAll('.bill-row')].indexOf(row);data.bills[index].frequency=select.value;renderBillEditor()})}
function setPartnerContributionEnabled(enabled){document.querySelector('#partnerEnabled').checked=enabled;document.querySelector('#partnerAmountField').classList.toggle('is-disabled',!enabled);document.querySelector('#partnerInput').disabled=!enabled}function openSettings(){originalTheme=theme;originalMode=mode;['wage','partner','rentTwo'].forEach(k=>document.querySelector(`#${k}Input`).value=data[k]);setPartnerContributionEnabled(data.partner>0);setPlanDirty(false);renderAppearanceEditor();renderBillEditor();document.querySelector('#settingsDialog').showModal()}
document.querySelector('#settingsButton').onclick=openSettings;document.querySelector('#previousMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()-1);render()};document.querySelector('#nextMonth').onclick=()=>{cursor.setMonth(cursor.getMonth()+1);render()};document.querySelector('#themeSelect').onchange=e=>{theme=e.target.value;localStorage.setItem('money-map-theme',theme);applyAppearance();updateThemePreview()};document.querySelector('#darkModeInput').onchange=e=>{mode=e.target.checked?'dark':'light';localStorage.setItem('money-map-mode',mode);applyAppearance()};document.querySelector('#partnerEnabled').onchange=e=>{setPartnerContributionEnabled(e.target.checked);setPlanDirty()};['wageInput','partnerInput','rentTwoInput'].forEach(id=>document.querySelector(`#${id}`).oninput=()=>setPlanDirty());
document.querySelector('#listViewButton').onclick=()=>{activeView='list';document.querySelector('#paymentList').hidden=false;document.querySelector('#calendarView').hidden=true;document.querySelector('#listViewButton').classList.add('active');document.querySelector('#calendarViewButton').classList.remove('active')};document.querySelector('#calendarViewButton').onclick=()=>{activeView='calendar';document.querySelector('#paymentList').hidden=true;document.querySelector('#calendarView').hidden=false;document.querySelector('#calendarViewButton').classList.add('active');document.querySelector('#listViewButton').classList.remove('active')};
document.querySelector('#addBill').onclick=()=>{data.bills.push({id:`bill-${Date.now()}`,name:'New bill',amount:0,day:1,frequency:'monthly',month:0});setPlanDirty();renderBillEditor()};
document.querySelector('#settingsForm').addEventListener('submit',e=>{if(e.submitter?.id!=='saveSettings')return;e.preventDefault();data.wage=Number(document.querySelector('#wageInput').value)||0;data.partner=document.querySelector('#partnerEnabled').checked?(Number(document.querySelector('#partnerInput').value)||0):0;data.rentTwo=Number(document.querySelector('#rentTwoInput').value)||0;document.querySelectorAll('.bill-row').forEach((row,i)=>{const frequency=row.querySelector('[data-f=frequency]').value,windowValue=row.querySelector('[data-f=window]')?.value.split('-').map(Number)||[];data.bills[i]={...data.bills[i],name:row.querySelector('[data-f=name]').value,amount:Number(row.querySelector('[data-f=amount]').value)||0,frequency,month:frequency==='annual'?Number(row.querySelector('[data-f=month]').value):0,date:frequency==='one-off'?row.querySelector('[data-f=date]').value:'',startDay:frequency==='window'?windowValue[0]:undefined,endDay:frequency==='window'?windowValue[1]:undefined,day:(frequency==='monthly'||frequency==='variable')?Math.min(31,Math.max(1,Number(row.querySelector('[data-f=day]').value)||1)):1}});localStorage.setItem('money-map-data',JSON.stringify(data));savingSettings=true;document.querySelector('#settingsDialog').close();render()});
document.querySelector('#settingsDialog').addEventListener('close',()=>{if(!savingSettings){data=restoreData();render()}savingSettings=false;setPlanDirty(false)});
let detailBillName='';function openDetails(name){const bill=data.bills.find(b=>b.name===name);if(!bill)return;detailBillName=name;document.querySelector('#detailsTitle').textContent=name;document.querySelector('#detailsMethod').value=bill.method||'';document.querySelector('#detailsReference').value=bill.reference||'';document.querySelector('#detailsNotes').value=bill.notes||'';document.querySelector('#detailsDialog').showModal()}document.querySelector('#detailsForm').addEventListener('submit',e=>{if(e.submitter?.id!=='saveDetails')return;e.preventDefault();const bill=data.bills.find(b=>b.name===detailBillName);if(bill){bill.method=document.querySelector('#detailsMethod').value;bill.reference=document.querySelector('#detailsReference').value;bill.notes=document.querySelector('#detailsNotes').value;localStorage.setItem('money-map-data',JSON.stringify(data))}document.querySelector('#detailsDialog').close()});
function openHistory(){const snapshots=Object.keys(localStorage).filter(key=>key.startsWith('money-map-history-')).map(key=>JSON.parse(localStorage.getItem(key))).sort((a,b)=>new Date(b.month)-new Date(a.month));document.querySelector('#historyList').innerHTML=snapshots.length?snapshots.map(item=>`<article class="history-card"><div><h3>${new Date(item.month).toLocaleDateString('en-GB',{month:'long',year:'numeric'})}</h3><p>${money(item.income)} in · ${money(item.outgoing)} out</p></div><div class="history-leftover"><strong>${money(item.leftover)}</strong><small>left after plan</small></div></article>`).join(''):'<div class="history-empty">No monthly snapshots yet. Open Settings and choose “Save month snapshot” when you want to keep a record.</div>';document.querySelector('#historyDialog').showModal()}document.querySelector('#historyButton').onclick=openHistory;
document.querySelector('#saveSnapshot').onclick=()=>{const list=payments(),income=list.filter(i=>i.type==='income').reduce((s,i)=>s+i.amount,0),outgoing=list.filter(i=>i.type==='outgoing').reduce((s,i)=>s+(Number(localStorage.getItem(actualKey(i)))||i.amount),0),key=`money-map-history-${cursor.getFullYear()}-${cursor.getMonth()}`;localStorage.setItem(key,JSON.stringify({month:cursor.toISOString(),income,outgoing,leftover:income-outgoing,savedAt:new Date().toISOString()}));document.querySelector('#notificationStatus').textContent='Monthly snapshot saved in this browser.'};document.querySelector('#exportBackup').onclick=()=>{const backup={version:1,exportedAt:new Date().toISOString(),plan:data,storage:Object.fromEntries(Object.entries(localStorage).filter(([key])=>key.startsWith('money-map-')))};const url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='money-map-backup.json';link.click();URL.revokeObjectURL(url)};document.querySelector('#importBackup').onchange=e=>{const file=e.target.files[0];if(!file)return;if(!window.confirm('Importing a backup replaces your current Money Map data in this browser. Continue?')){e.target.value='';return}const reader=new FileReader();reader.onload=()=>{try{const backup=JSON.parse(reader.result);if(!backup.plan)throw Error();for(const [key,value] of Object.entries(backup.storage||{}))localStorage.setItem(key,value);localStorage.setItem('money-map-data',JSON.stringify(backup.plan));data=restoreData();render();document.querySelector('#notificationStatus').textContent='Backup restored successfully.'}catch{document.querySelector('#notificationStatus').textContent='That backup file could not be restored.'}};reader.readAsText(file)};document.querySelector('#resetLocalData').onclick=()=>{if(!window.confirm('Reset all Money Map data saved in this browser? This cannot be undone unless you exported a backup.'))return;Object.keys(localStorage).filter(key=>key.startsWith('money-map-')).forEach(key=>localStorage.removeItem(key));location.reload()};
document.querySelector('#notifyButton').onclick=async()=>{if(!('Notification'in window)){document.querySelector('#notificationStatus').textContent='Notifications are not supported in this browser.';return}const p=await Notification.requestPermission();document.querySelector('#notificationStatus').textContent=p==='granted'?'Reminders enabled. Here is a test notification.':'Notification permission was not granted.';if(p==='granted')new Notification('Money Map',{body:'Your bill reminders will appear here when push scheduling is connected.'})};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=26',{updateViaCache:'none'}).then(registration=>registration.update());applyAppearance();render();fetch('https://www.gov.uk/bank-holidays.json').then(r=>r.ok?r.json():Promise.reject()).then(h=>{bankHolidays=new Set(h['england-and-wales'].events.map(e=>e.date));render()}).catch(()=>document.querySelector('#notificationStatus').textContent='Bank-holiday dates could not be loaded, so this view currently applies weekend adjustments only.');setTimeout(()=>document.querySelector('#splashScreen').classList.add('is-hidden'),1600);
